[package]
name = "marsdown"
version = "0.1.9"
authors = ["Wafelack <wafelack@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lines_from_file = "0.1.2"